# Generated by Django 4.0.4 on 2022-05-21 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id_encuesta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_encuesta', models.CharField(max_length=100, verbose_name='Nombre de la Encuesta')),
                ('fecha', models.DateTimeField(verbose_name='Fecha de la Encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaEncuestada',
            fields=[
                ('id_persona_encuestada', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100, verbose_name='Nombre Completo de la Persona Encuestada')),
                ('sexo', models.CharField(max_length=10, verbose_name='Sexo de la Persona Encuestada')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo de la Persona Encuestada')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=100, verbose_name='Pregunta')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.encuesta', verbose_name='Encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEncuesta',
            fields=[
                ('id_tipo_encuesta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Tipo de Encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoEncuesta',
            fields=[
                ('id_resultado_encuesta', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.CharField(max_length=100, verbose_name='Respuesta')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.encuesta', verbose_name='Encuesta')),
                ('persona_encuestada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personaencuestada', verbose_name='Persona Encuestada')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pregunta', verbose_name='Pregunta')),
            ],
        ),
        migrations.AddField(
            model_name='encuesta',
            name='tipo_encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipoencuesta', verbose_name='Tipo de Encuesta'),
        ),
    ]
